### ISSUE TITLE
hasMultipleIntents to use OpenAI functions 

### ISSUE THREAD

**Issue by gharbat** [openchatai/OpenCopilot#108]
Currently, `hasMultipleIntents` is using conditional statement to tell if the user request contain multi intents (require multiple API calls to get done). 

Might be better to use OpenAI function to do that, something like:
```
Given these endpoints and their descriptions, please answer the question at the end:
getPets: to get all pets
createPet: to create a new pet
delete pet: delete a single pet


The question: "please delete the last pet"
```

The LLM should spit something like "yes" or any thing similar. 

```python
# llm-server/routes/root_service.py:76
    try:
        if hasMultipleIntents(text):
            return run_workflow(
                WorkflowData(text, swagger_text, headers, server_base_url)
            )
    except Exception as e:
        print(e)
```

**Comment by codebanesr** [comment]
there is another implementation similar to your suggestion here, we will switch to it
https://github.com/openchatai/OpenCopilot/blob/a1cb68645e8e7acaf8b45a5154863cb2c2f7342b/llm-server/utils/detect_multiple_intents.py
