### ISSUE TITLE
The copilot can not answer the question about the pet shop

### ISSUE THREAD

**Issue by eightrivers** [openchatai/OpenCopilot#119]
Hello, 

The application has been deployed in my machine, and there was no error but  a few warning during deployment. I created a demo of  pet shop, and tryied to chat with the OpenPilot. When I asked some questions just like, what is the highest mountain in Earth, the copilot gave the answer quickly. But if I answer questions related to the pet shop, the response is a error message: Error sending the message, Shown as below.  And if I sent new message, there was no response. seems  one of components does'nt work. 

Is there any tips for this issue?  Thanks a lot! 

Environment:
Ubuntu 20.04.6 LTS
16G RAM
Docker 24.0.6

![image](https://github.com/openchatai/OpenCopilot/assets/1868294/b3363c4f-6f64-456f-804b-2444a4e55fb5)

**Comment by eightrivers** [comment]
> Question - After this happened, does the entire application dies (extremely slow requests) or just the chat bubble?

Seems the entire application does not work. There is no response when trying to refresh the page, until run 'make restart' .

**Comment by eightrivers** [comment]
Is there any updates on this issue,,, Thanks!

**Comment by codebanesr** [comment]
I believe this was fixed a while back, closing
