### ISSUE TITLE
Implement Unlimited memory like MemGPT

### ISSUE THREAD

**Issue by Vossy** [openchatai/OpenCopilot#168]
Github: https://github.com/cpacker/MemGPT

Video: https://www.youtube.com/watch?v=QQ2QOPWZKVc

The problem it solves - always stays in context based on stored memory.

I believe this is a critical feature for any LLM-based assistant/copilot.

**Comment by codebanesr** [comment]
Memgpt in it's current state shouldn't be used as an increased latency would degrade user experience. We will keep it for later
