### ISSUE TITLE
Consistently getting "Workflow Name" as "None" in the API response according to bot even though no concept like this exists in my API

### ISSUE THREAD

**Issue by Azdaroth** [openchatai/OpenCopilot#367]
**Describe the bug**
Hi. I'm consistently getting "Workflow Name" as "None" in the API response according to bot even though no concept like this exists in my API, although it looks like something that is the part of Open Copilot when checking the code. 

Here is an example screenshot, although the same thing happens in different scenarios.

![Image 2023-12-06 at 6 46 09 PM](https://github.com/openchatai/OpenCopilot/assets/1833644/29dc99c9-989f-4526-b39e-a033fa6e5101)

Here is the config for the widget:

```
<script src="http://localhost:8888/pilot.js"></script>
            <script> // be aware to call this function when the document/window is ready.
            const options = {
              apiUrl: "http://localhost:8888/backend", // your base url where your are hosting OpenCopilot at (the API), usually it's http://localhost:5000/api
              // initialMessages: ["How are the things"], // optional: you can pass an array of messages that will be sent to the copilot when it's initialized
              token: "MYTOKEN",
              triggerSelector: "#triggerSelector", // the selector of the element that will trigger the copilot when clicked
              headers: {
                // optional: you can pass your authentication tokens to the copilot or any other header you want to send with every request
                Authorization: "Bearer THIS IS SECRET",
              },
              user:{
                name: "user"
              }
            }
            window.addEventListener("DOMContentLoaded", ()=>initAiCoPilot(options)); // window.onload
</script>


<span id="triggerSelector">Click me</span>

```
What's the source of the issue?

**Comment by Azdaroth** [comment]
After pulling the last changes form the _main_ branch I'm getting empty responses for anything related to API requests:

![Image 2023-12-07 at 7 26 06 AM](https://github.com/openchatai/OpenCopilot/assets/1833644/bf713d7f-da75-49ff-b8de-653217546b55)


 The swagger docs look fine, the token is valid, so I'm not really sure what the source of this problem is.

**Comment by codebanesr** [comment]
Hey Karol, I will look into this and get back to you. Can you share your
swagger file with me?

**Comment by codebanesr** [comment]
<img width="1105" alt="Screenshot 2023-12-07 at 4 23 35 PM" src="https://github.com/openchatai/OpenCopilot/assets/17947802/6123ff08-2a73-4633-823c-79e78db6482d">
Tried to create an account on the platform, the confirm email link seems to be broken! Can you share a staging authz key privately at 
s@opencopilot.so ?

**Comment by Azdaroth** [comment]
@codebanesr This is more like a private application and the API is semi-private, so this is expected that it won't work easily.

Sharing tokens would require some extra setup, so maybe what I'll do is to try it with some different swagger docs, maybe for Trello. Just to be able to tell whether the problem is related to the swagger schema or is it something else.

**Comment by Azdaroth** [comment]
@codebanesr alternatively, is it something that you would be able to verify easily on your side if it works fine for any other API? just wondering if the issue could be potentially caused by one of the recent commits.

**Comment by codebanesr** [comment]
https://github.com/openchatai/OpenCopilot/issues/367#issuecomment-1845346637
One thing that i found out of the box, is that description and summary wasn't very clear on the swagger file you shared. 

We use `prance` library for parsing and it seems like the server validation is failing. A quick fix for this would be to move `/api/ota/v1` into the api themselves instead of `baseUrl`. It should work after that. (I will mark this as a bug and push a fix for it)


Also, would you mind joining our discord server ?
https://discord.gg/42gJXHzz6S

**Comment by codebanesr** [comment]
Yup

**Comment by codebanesr** [comment]
Hey @Azdaroth ,
Just sent a DM over discord. Let's take it from there.
