### ISSUE TITLE
Copilot Memory

### ISSUE THREAD

**Issue by gharbat** [openchatai/OpenCopilot#39]
#### Description
Add the ability for Copilot to remember conversation context. This feature will let users ask for changes to previous requests more easily.

#### What We Need
- Copilot should remember past conversations.
- Users should be able to ask for changes to what was said before.
- Make sure it doesn't slow Copilot down.

**Comment by Vossy** [comment]
MemGPT!

Github: https://github.com/cpacker/MemGPT

Video: https://www.youtube.com/watch?v=QQ2QOPWZKVc
