### ISSUE TITLE
create new flow error

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [openchatai/OpenCopilot#396]
create new flow error：
The front UI did not report an error, but did not generate the corresponding flow. Background logs are as follows:

mongodb                   | {"t":{"$date":"2023-12-14T03:07:30.004+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.21.0.9:52410","uuid":{"uuid":{"$uuid":"037287f1-0212-418b-b6cb-94b6b4006bff"}},"connectionId":9,"connectionCount":9}}
mongodb                   | {"t":{"$date":"2023-12-14T03:07:30.007+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn9","msg":"client metadata","attr":{"remote":"172.21.0.9:52410","client":"conn9","doc":{"driver":{"name":"PyMongo","version":"4.5.0"},"os":{"type":"Linux","name":"Linux","architecture":"aarch64","version":"6.4.16-linuxkit"},"platform":"CPython 3.9.18.final.0"}}}
mongodb                   | {"t":{"$date":"2023-12-14T03:07:30.012+00:00"},"s":"I",  "c":"ACCESS",   "id":6788604, "ctx":"conn9","msg":"Auth metrics report","attr":{"metric":"acquireUser","micros":0}}
mongodb                   | {"t":{"$date":"2023-12-14T03:07:30.023+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn9","msg":"Successfully authenticated","attr":{"client":"172.21.0.9:52410","isSpeculative":true,"isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"dbuser","db":"admin","result":0,"metrics":{"conversation_duration":{"micros":10364,"summary":{"0":{"step":1,"step_total":2,"duration_micros":153},"1":{"step":2,"step_total":2,"duration_micros":40}}}},"extraInfo":{}}}
mongodb                   | {"t":{"$date":"2023-12-14T03:07:30.025+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn9","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":2}}
opencopilot-llm-server-1  | 172.21.0.12 - - [14/Dec/2023 03:07:35] "POST /backend/flows/b/56a24e86-ade4-4b47-a626-9f9435b3654c HTTP/1.0" 201 -
opencopilot-nginx-1       | 192.168.65.1 - - [14/Dec/2023:03:07:35 +0000] "POST /backend/flows/b/56a24e86-ade4-4b47-a626-9f9435b3654c HTTP/1.1" 201 59 "http://localhost:8888/copilot/56a24e86-ade4-4b47-a626-9f9435b3654c/flows" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
opencopilot-llm-server-1  | 172.21.0.12 - - [14/Dec/2023 03:07:35] "GET /backend/flows/get/b/56a24e86-ade4-4b47-a626-9f9435b3654c?page=1 HTTP/1.0" 200 -
opencopilot-nginx-1       | 192.168.65.1 - - [14/Dec/2023:03:07:35 +0000] "GET /backend/flows/get/b/56a24e86-ade4-4b47-a626-9f9435b3654c?page=1 HTTP/1.1" 200 61 "http://localhost:8888/copilot/56a24e86-ade4-4b47-a626-9f9435b3654c/flows" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
opencopilot-llm-server-1  | 172.21.0.9 - - [14/Dec/2023 03:07:39] "GET /healthcheck HTTP/1.1" 200 -

**Comment by gharbat** [comment]
Will take care of it in the next release - thanks for reporting!

**Comment by gharbat** [comment]
A fix was deployed today (along with a new way to create flows) - let me know how is it!

**Comment by codebanesr** [comment]
@shanmu-raoyunfei feel free to open the ticket if issue persists, as @gharbat mentioned this should be fixed now
