### ISSUE TITLE
Knowledge base unavailable

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [openchatai/OpenCopilot#397]
I successfully uploaded a pdf knowledge document, but did not invoke the knowledge base while using opencopilot.

**Comment by codebanesr** [comment]
Can you please share worker logs after uploading the pdf. Moreover if you could check `http://localhost:6333/dashboard` and confirm whether or not you see the pdf being ingested

**Comment by codebanesr** [comment]
There was a missing dependency on lxml parser. It has been fixed now
