### ISSUE TITLE
Error creating a new copilot

### ISSUE THREAD

**Issue by WKaiH123** [openchatai/OpenCopilot#421]
**Describe the bug**
I can't create a new copilot.
![image](https://github.com/openchatai/OpenCopilot/assets/95872527/548b4062-58ca-4382-a1f1-33d2a77388cd)

**Comment by gharbat** [comment]
Can you run `make logs` and share the error that happens when you try to create a copilot?

**Comment by WKaiH123** [comment]
When I try to create a new copilot, I get the following error:
![image](https://github.com/openchatai/OpenCopilot/assets/95872527/4121a396-114d-4762-9485-cc5459b13066)

**Comment by WKaiH123** [comment]
![image](https://github.com/openchatai/OpenCopilot/assets/95872527/48c39a2a-b759-4e30-9f82-285ba0a2912e)

**Comment by gharbat** [comment]
Can you try to run `make restart`? and then give it another try?

**Comment by codebanesr** [comment]
I encountered a similar issue, looking into it
```
2023-12-19 17:46:54     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-19 17:46:54   File "/app/routes/copilot/copilot_controller.py", line 41, in create_new_copilot
2023-12-19 17:46:54     user = get_user_by_email(get_username_from_request(request))
```

**Comment by tpmccallum** [comment]
I have this same error:
![Screenshot 2023-12-20 at 12 30 06](https://github.com/openchatai/OpenCopilot/assets/9831342/a759fb21-2bac-494a-87e3-b3cca3554995)

At the same time the above is happening, the logs are outputting these lines:
```
llm-server_1  | 192.168.80.8 - - [20/Dec/2023 02:30:06] "GET /healthcheck HTTP/1.1" 200 -
llm-server_1  | 192.168.80.8 - - [20/Dec/2023 02:30:17] "GET /healthcheck HTTP/1.1" 200 -
llm-server_1  | 192.168.80.8 - - [20/Dec/2023 02:30:27] "GET /healthcheck HTTP/1.1" 200 -
llm-server_1  | 192.168.80.8 - - [20/Dec/2023 02:30:37] "GET /healthcheck HTTP/1.1" 200 -
```

**Comment by tpmccallum** [comment]
Seems it is an error:
```
POST http://localhost:8888/backend/copilot/ net::ERR_CONNECTION_REFUSED
```
It seems to be hardwired to `localhost`

**Comment by codebanesr** [comment]
Please try to restart nginx once, and let me know if that resolves the issue

**Comment by tpmccallum** [comment]
Can you please let me know what command I need to restart nginx once?
Thanks so much.

**Comment by codebanesr** [comment]
`docker compose restart nginx` or `docker-compose restart nginx` from root
repository, depending on which docker version you use

**Comment by tpmccallum** [comment]
```
$ docker compose restart nginx
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Restarting 1/1
 ✔ Container opencopilot_nginx_1  Started             
```

Still the same error, but this is a new message in the logs:

```
dashboard_1   |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

```

**Comment by codebanesr** [comment]
- "The client (a laptop) I am using to access the server is trying to connect to the localhost (laptop)." 
If i undertand correctly, you use the ip of the server and not localhost, when calling the api on the server ? 

Also @ah7255703 can you check the issue with sharp?

**Comment by tpmccallum** [comment]
Yes, interacting with the ip of the server (not localhost). However, the browser's console is outputting errors relating to contacting localhost with requests using the GET and POST verbs:
![Screenshot 2023-12-20 at 14 22 26](https://github.com/openchatai/OpenCopilot/assets/9831342/0b0915a4-0fe5-4dcb-a44f-ccc1998df1dc)

**Comment by tpmccallum** [comment]
I went ahead and updated `vi ./dashboard/data/base-url.ts` from:

```ts
export const baseUrl = 'http://localhost:8888'
```

to 

```ts
export const baseUrl = 'http://my-open-chat-ai-server:8888'
```

The error in the console of my browser has been resolved.

**Comment by WKaiH123** [comment]
@tpmccallum Hi, after I modified the base-url.ts file, I still didn't solve the problem. How did you solve it?

**Comment by WKaiH123** [comment]
Problem solved, thank you very much!
