### ISSUE TITLE
mysql_1       | exec /usr/local/bin/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by tpmccallum** [openchatai/OpenCopilot#429]
**Describe the bug**
A reoccuring error after `make install` or `make restart`

```bash
mysql_1       | exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

**To Reproduce**
1. git clone repo
2. cp llm-server/.env.example to llm-server/.env
3. add `OPENAI_API_KEY` to that llm-server/.env file
4. make install

**Expected behavior**
To see localhost:8888 working

**Desktop (please complete the following information):**
- Linux Ubuntu x86_64 GNU/Linux

<img width="877" alt="Screenshot 2023-12-20 at 08 42 56" src="https://github.com/openchatai/OpenCopilot/assets/9831342/046cab85-f707-4288-ae2a-78c4756c895d">

**Comment by gharbat** [comment]
this usually arises due to a mismatch between the architecture of the Docker image and the architecture of your host system. but as you're using an x86_64 it seems it's something else, can you try to re-build the project one more time? if that does not work I can spend some time debugging it

**Comment by tpmccallum** [comment]
Thanks for the speedy reply @gharbat 

I did the following:
```
docker-compose down -v
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker container prune
docker volume prune
```

Then, `make install`, and it worked.
Thanks again.
