### ISSUE TITLE
Error sending the message.

### ISSUE THREAD

**Issue by WKaiH123** [openchatai/OpenCopilot#433]
**Describe the bug**
I have deployed opencopilot to my server and configured OPENAI_API_KEY. I simply created a copilot. I found that copilot couldn't chat with me.
If you can help me solve this problem, I would be very grateful.
![image](https://github.com/openchatai/OpenCopilot/assets/95872527/03ee8053-afa7-40e9-986e-82ea7892647b)

**Comment by codebanesr** [comment]
@WKaiH123 please share server logs here

**Comment by WKaiH123** [comment]
@codebanesr How should I view the log messages?

**Comment by codebanesr** [comment]
docker compose logs -f llm-server
From root directory


You can do the same for other containers too

**Comment by WKaiH123** [comment]
![image](https://github.com/openchatai/OpenCopilot/assets/95872527/4b6308d2-a799-4c18-a0c3-b5a79720577f)

**Comment by codebanesr** [comment]
Ok two things to verify
1. Is your openai api key correct
2. Is openai available in the region your server is hosted
