### ISSUE TITLE
I cannot chat ưith·

### ISSUE THREAD

**Issue by alice210897** [openchatai/OpenCopilot#541]
I have not received any response for my request, please help 
![image](https://github.com/openchatai/OpenCopilot/assets/156877177/be312e25-2200-4013-8e93-2fa5c0953de8)

**Comment by ah7255703** [comment]
Hey @alice210897 are you using the cloud application or the OSS one ? 
if you are using the OSS can u share the llm-server logs from docker.

**Comment by alice210897** [comment]
I use the cloud and I still cannot chat with My First Copilot anymore. I used to chat with it in a few days ago

**Comment by alice210897** [comment]
I also did change from Chrome to Internet explore, firefox but I still cannot chat with it, please help

**Comment by codebanesr** [comment]
Hey @alice210897 ,
Feel free to setup a  calendar invite, i can look into it
s@opencopilot.so
