### ISSUE TITLE
"Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning

### ISSUE THREAD

**Issue by tpmccallum** [openchatai/OpenCopilot#616]
**Describe the bug**
Getting an ffmpeg error in the `make logs`

```bash
llm-server-1  |  * Restarting with stat
llm-server-1  | /usr/local/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
llm-server-1  |   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```

**To Reproduce**
1. git clone
2. make install
3. (In a new terminal.) make logs

**Expected behavior**
No error

**Screenshots**

<img width="1746" alt="Screenshot 2024-02-08 at 09 03 09" src="https://github.com/openchatai/OpenCopilot/assets/9831342/2f108fa6-3087-44a5-875c-52123f8ca8df">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome (but not really a browser issue)
 - Tip of main ([3396400970d68c9fc3373a5572598fa574b29465](https://github.com/openchatai/OpenCopilot/commit/3396400970d68c9fc3373a5572598fa574b29465))

**Additional context**
The macOS has ffmpeg installed e.g.

```bash
ffmpeg -h
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

**Comment by codebanesr** [comment]
hey @tpmccallum , this should usually not affect the copilot performance, but we will add support for it. 

@ah7255703 can help us with that.
