### ISSUE TITLE
GET http://localhost:8888/backend/copilot/ net:: ERR_CONNECTION_REFUSED 929-4cfffbd6894a23df.js:6

### ISSUE THREAD

**Issue by mikeyang01** [openchatai/OpenCopilot#623]
[
![CleanShot 2024-02-13 at 22 39 53@2x](https://github.com/openchatai/OpenCopilot/assets/2081093/265adcee-4f1e-48af-bc65-d04a34b42b64)
](url)

I deployed the code on Ubuntu vps And make install, failed to create copilot
how to change localhost to remote Server? thanks

**Comment by codebanesr** [comment]
you will have to change it in `dashboard/.env` file, 

SECRET=XXXXx

NEXTAUTH_URL=<server_ip:port>

NEXT_PUBLIC_BASE_URL=<server_ip:port>
NEXT_PUBLIC_BACKEND_API_URL=<server_ip:port>

**Comment by mikeyang01** [comment]
> you will have to change it in `dashboard/.env` file,
> 
> SECRET=XXXXx
> 
> NEXTAUTH_URL=<server_ip:port>
> 
> NEXT_PUBLIC_BASE_URL=<server_ip:port> NEXT_PUBLIC_BACKEND_API_URL=<server_ip:port>

thanks, what is SECRET=YourSecretKey here?

**Comment by codebanesr** [comment]
@mikeyang01 I want to make sure I'm on the right track. Did you deploy your code to an Ubuntu VPS, and are you looking to update the client configuration so it points to the correct server address instead of localhost?

**Comment by mikeyang01** [comment]
Thanks for the reply. IP address works for now. close this issue 🌹 


<br class="Apple-interchange-newline">
