### ISSUE TITLE
upload a pdf as datasource

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenCopilot#650]
How can i set up the limitation of size from PDF?

**Comment by codebanesr** [comment]
You can set it up from nginx.conf file
- `OpenCopilot/container_config`
```
 http {
 ...
 client_max_body_size 100M;
 }
```

Read more: https://docs.rackspace.com/docs/limit-file-upload-size-in-nginx

**Comment by JuergenCornely** [comment]
Thanks a lot ..
 if searched at the llm server settings
