### ISSUE TITLE
send button is not clickable, but enter key works fine.

### ISSUE THREAD

**Issue by mikeyang01** [openchatai/OpenCopilot#656]
![ygr074s18atnre9urlCe8NxJ5JyuYWKofueHLa6j](https://github.com/openchatai/OpenCopilot/assets/2081093/901fcb5d-c526-4a13-987f-ffd83ad18aa7)
![CleanShot 2024-02-25 at 17 10 37@2x](https://github.com/openchatai/OpenCopilot/assets/2081093/30d9f209-f8ee-4293-b76d-7e5d47c4dd10)
The send button is not gray out, but still unclickable. Enter key works fine.

source code is below
`R.jsx("button",{onClick:a,className:"text-xl disabled:opacity-40 disabled: pointer-events-none disabled: cursor-not-allowed  text-[#5e5c5e]  transition-all",disabled:i||!o\\`

`<button class="text-xl disabled:opacity-40 disabled: pointer-events-none disabled: cursor-not-allowed  text-[#5e5c5e]  transition-all" disabled=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send-horizontal rtl:rotate-180"><path d="m3 3 3 9-3 9 19-9Z"></path><path d="M6 12h16"></path></svg></button>`

**Comment by mikeyang01** [comment]
@codebanesr 
I hope this message finds you well.  I would appreciate if you could take a look at. The issue description is above. I believe your insights and guidance would greatly help in resolving this matter.

I really admire your dedication in maintaining and improving it. If you could spare some time to review and provide feedback on this issue, it would be much appreciated.

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards,

**Comment by ah7255703** [comment]
Thanks for submitting. 
the issue has been resolved in this pr https://github.com/openchatai/OpenCopilot/pull/667
