### ISSUE TITLE
Upload of Documents

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenCopilot#666]
There seems to be u bug uploading Documents in the latest Version. I ve merged today and now when i upload a file now i seen a error in the logfile:

 [2024-02-28 08:21:07,495: WARNING/ForkPoolWorker-1]   File "/usr/local/lib/python3.9/site-packages/langchain/document_loaders/pdf.py                       ", line 100, in __init__
workers_1     |     raise ValueError("File path %s is not a valid file or url" % self.file_path)

any hints?

**Comment by codebanesr** [comment]
Please take a pull, should be resolved now.

**Comment by codebanesr** [comment]
@JuergenCornely We added support for s3 file uploads in the last pr. 
Read more here: https://github.com/openchatai/OpenCopilot/tree/main/llm-server#file-storage-configuration
