### ISSUE TITLE
Can we connect this to a realtime database like postgres?

### ISSUE THREAD

**Issue by sathyapriyaa13** [openchatai/OpenCopilot#677]
I see the api calls being defined for each request type in swagger file. Can we connect this to a realtime database like postgres?

**Comment by codebanesr** [comment]
I don't fully get it, by realtime database, do you mean some sort of wrapper that can automatically generate the crud endpoints ?

**Comment by sathyapriyaa13** [comment]
Nope, I meant about connecting openCopilot to an existing database
connection and being able to chat with users regarding that.

**Comment by codebanesr** [comment]
well, you can add another environment variable that should connect
MYSQL_URI=mysql+aiomysql://dbuser:dbpass@localhost:3307/opencopilot
---


please visit https://github.com/openchatai/OpenCopilot/blob/60917e8fab3de79bbe18227306b742291bd0e3ef/llm-server/utils/llm_consts.py, for a list of environment variables

**Comment by sathyapriyaa13** [comment]
***@***.***:port/dbname -- this doesn't
actually work?
