### ISSUE TITLE
"Table 'opencopilot.chatbots' doesn't exist"

### ISSUE THREAD

**Issue by NaMoCv** [openchatai/OpenCopilot#679]
**Describe the bug**
0.0.88-beta
use azure
.env:
OPENAI_API_TYPE=azure
EMBEDDING_PROVIDER=azure
AZURE_OPENAI_EMBEDDING_MODEL_NAME=text-embedding-ada-002
AZURE_OPENAI_API_TYPE=azure
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_DEPLOYMENT_NAME=gpt-35-turbo
AZURE_OPENAI_COMPLETION_MODEL=gpt-35-turbo
AZURE_OPENAI_API_VERSION=2023-07-01-preview
AZURE_OPENAI_API_BASE=https://xxx.openai.azure.com/

make install or make migrate
"Table 'opencopilot.chatbots' doesn't exist"

**Comment by NaMoCv** [comment]
if set OPENAI_API_KEY=xxx, it will pass.

**Comment by codebanesr** [comment]
please run `make migrate` and `make restart`, it should fix the problem.
