### ISSUE TITLE
working with https

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenCopilot#704]
Hi all i need a helping hand to get it working with https. I v nginx up and running with https. But when i load the page it stops while miced content . The backend still reponses with http.....

**Comment by krcpr007** [comment]
take care of the config file of nginx

**Comment by JuergenCornely** [comment]
i tried about 2 days... for me the backen (llm) answers via http and that will be blocked....

**Comment by JuergenCornely** [comment]
is working now

**Comment by zsradu** [comment]
What exactly did you change here? I also have https issues (SSL)

**Comment by JuergenCornely** [comment]
i  ve added a .env to the dashboard container with the following:

NEXTAUTH_URL=http://localhost:8888/backend/
NEXT_PUBLIC_BASE_URL=https://localhost:8888/backend
NEXT_PUBLIC_BACKEND_API_URL=https://localhost:8888/backend
NEXT_PUBLIC_LLM_CONTAINER_URL=https://localhost:8888/backend
