### ISSUE TITLE
make_api_request() is missing a required argument called extra_params

### ISSUE THREAD

**Issue by nicholaskoerfer** [openchatai/OpenCopilot#714]
**Describe the bug**
When I create an action (with a header for authentication) and with or without additional parameters, I get the following error in the chat:

An error occurred while trying to process your request. It seems that the function make_api_request() is missing a required argument called extra_params. Please make sure to provide the necessary extra_params argument when calling the make_api_request() function.

**To Reproduce**
1. Open chat
2. Enter a prompt that would start a defined action
3. See error

**Expected behavior**
OpenCopilot would call API and respond without any problems

**Server (please complete the following information):**
 - OS: Ubuntu 22.04LTS
 - OpenCopilot Version: 0.0.90

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Tested: Brave
 - Version: Chromium 122.0.6261.128

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] NOT TESTED

**Additional context**
Version 0.0.89 worked (though there were always json parsing errors), but not this error

**Comment by codebanesr** [comment]
pelase take the lastest pull from main, this should be fixed now
