### ISSUE TITLE
Local development error occurred

### ISSUE THREAD

**Issue by an9xyz** [openchatai/OpenCopilot#75]
**Describe the bug**

access url http://localhost:8888/app

"An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error."

backend error
```
opencopilot-backend-1  |
opencopilot-backend-1  |    INFO  Server running on [http://0.0.0.0:5000].
opencopilot-backend-1  |
opencopilot-backend-1  |   Press Ctrl+C to stop the server
opencopilot-backend-1  |
opencopilot-backend-1  |   2023-09-20 02:11:47 ................................................... ~ 0s
```

_Failed__ to connect to localhost port 5000 after 5 ms: Couldn't connect to server

btw: Where is dashboard/.env.example?
`
cp -n dashboard/.env.example dashboard/.env 2>/dev/null || true
`

**Comment by bh4ffu** [comment]
same issue, when the issue can be resolved?

**Comment by cnnbevan** [comment]
"An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error."
