### ISSUE TITLE
content -> none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by bickkysahani** [openchatai/OpenCopilot#8]
I am trying to run this locally but keep getting this error

![image](https://github.com/openchatai/OpenCopilot/assets/49335486/7925d080-d930-4888-837c-0aa2a965bbbb)

![image](https://github.com/openchatai/OpenCopilot/assets/49335486/90e0e348-95cd-40f5-b560-1957a3cc09e1)

this is my specs

![image](https://github.com/openchatai/OpenCopilot/assets/49335486/5f8d808c-9644-47b4-870a-af3eb8262dfc)

**Comment by bickkysahani** [comment]
> Can you share the swagger.json file you used?
uploading json file is not supported in github issues so i have shared screenshots of it
<img width="882" alt="Screenshot 2023-08-26 at 15 43 21" src="https://github.com/openchatai/OpenCopilot/assets/49335486/0d8eedf6-893e-4519-b8ba-ef43c7dbc1c7">
<img width="882" alt="Screenshot 2023-08-26 at 15 43 52" src="https://github.com/openchatai/OpenCopilot/assets/49335486/7f1cd544-9b58-4a18-8a79-d906a8ca6954">
<img width="882" alt="Screenshot 2023-08-26 at 15 43 59" src="https://github.com/openchatai/OpenCopilot/assets/49335486/138939c9-dd76-47d0-ae33-4f39f12bfca1">

**Comment by shochdoerfer** [comment]
I am running into the same error for both my own Swagger config as well as for the Petstore Swagger example.

**Comment by codebanesr** [comment]
we have changed the swagger parser. The issue should be gone now. Feel free to open if issue persists
