### ISSUE TITLE
name 'text' is not defined

### ISSUE THREAD

**Issue by go-laoji** [openchatai/OpenCopilot#85]
/app/app.py:68: UserWarning: name 'text' is not defined

https://github.com/openchatai/OpenCopilot/blob/ee47f1d40ed9489b31912fc80416fc7b09fde33e/llm-server/app.py#L66

**Comment by codebanesr** [comment]
Hey @go-laoji ,
There was an issue with the last pr. I have raised a fix. Will merge it soon.

You can view the changeset here
https://github.com/openchatai/OpenCopilot/pull/86

**Comment by codebanesr** [comment]
This has been fixed in the latest release. @go-laoji please take a pull from main
